### PR TITLE
Assignment 5

### PR DESCRIPTION
**Pull request by NarySar**

### CODE REVIEW

**Comment by gaiborjosue** [comment]
Hello @NarySar, for homework 5, I see that you submitted the screenshots and picture. However, in the github pages I can only see the inkman, it seems you didn't push nothing to the 05 folder.

**Comment by NarySar** [comment]
Hi Edward,

Really! Thank you for letting know. Do I have to delete inkman first and then push to the 05 folder? Please advise.

Thank you,
Chansovannary

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gaiborjosue** [comment]
Hello @NarySar,

In 05 you should mirror the same environment you have locally. In other words, we don't need the inkman, we need your assignment. Thus, feel free to delete the inkman and upload your index instead (together with the 3D meshes of course).

**Comment by NarySar** [comment]
That sounds good, but I don't have my laptop with me can I do them when I get home?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gaiborjosue** [comment]
Sure, however, you will still loose some points for form submission since this is post-submission.

**Comment by NarySar** [comment]
That's fine, thank you so much for let me submit again.

Sincerely,
Nary

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gaiborjosue** [comment]
Hello @NarySar,

Although you created a new commit, I can only grade your submission. Big part of the homework is to verify github pages, as it is the only way we can interact with your project. 

Thus, I won't be able to give you credit for the three js part.

**Comment by NarySar** [comment]
Thank you for letting me know, I did summit 3D meshes last night with the form. Are you unable to view it? Also, you told me to push a 3D meshes again. So, I did commit it again in Github. Thank you.

sincerely,
Chansovannary
________________________________

**Comment by gaiborjosue** [comment]
Yes, you got credit for the meshes, however, the three js part required you to display those meshes through github pages.

As mentioned, you were only deducted points in the respective areas.

**Comment by gaiborjosue** [comment]
In terms of feedback, here is a little bit more:

1. No color functionality in the gui.
2. Rotation doesn't work correctly.
3. No change material option in the GUI.

Thanks.

**Comment by NarySar** [comment]
I appreciate your feedback and thank you for looking into my code. Hope you have a great night.

Sincerely,
Chansovannary

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
