### PR TITLE
HW-5

### PR DESCRIPTION
**Pull request by UpendraThota**

### CODE REVIEW

**Comment by gaiborjosue** [comment]
Hello @UpendraThota while trying to access the website, I am getting this error:

image

**Comment by UpendraThota** [comment]
Hi Edward,

Oh sorry for that but it was working fine in my local. As deadline passed I cant resubmit again it seems. Requesting you grade for the fifth assignment and let me know .


Regards,
Upendra
________________________________

**Comment by gaiborjosue** [comment]
Hello,

I can only grade on what I can see on the github pages.

Here is the feedback for the homework:
1. You didn't submit the three js screenshot, you only submitted your poly cam mesh.
2. You didn't submit the 3D printed mesh, only the poly cam mesh.
3. No three js visualization, only your GUI loads.

Always, before submitting check your github pages, this is crucial since we are now 5 homeworks-in the semester. As always, feel free to reach out in the Help channel if you need any help.

Have a great night!

**Comment by UpendraThota** [comment]
Hi Edward,

I just now as my fifth assignment  grade as it showing 45 out of 299. In my local Its working fine at that time, perhaps I didnt run when I pull on github. Since, this is the foirst time i was faced this issue. Requesting you excuse this time and regrade my assignment one more time and give some more grade on it. This will impact my overall grade on this subject and I dont want that. So, Requesting you please add some more marks on it.


Regards,
Upendra
________________________________

**Comment by gaiborjosue** [comment]
Hello @UpendraThota,

I completely understand your concern. However, please read the feedback I gave you.

You didn't submit the required files. There was no 3D-printed mesh picture. 

Since this assignment had an extension and was two weeks long, making sure GitHub pages work before submitting the assignment is crucial.

**Pull request closed without merging**
