### PR TITLE
Assignment - 02

### PR DESCRIPTION
**Pull request by rishankumb**

### CODE REVIEW

**Comment by gaiborjosue** [comment]
Hello @rishankumb, sadly, you did not activate GitHub pages. So, we won't be able to test your website/assignment. We can see the code but not test if it works. On the same note, you submitted a link to your repo's main tree instead of your website hosted in GitHub pages. Thanks for your design; it is pretty nice. Thanks

**Comment by rishankumb** [comment]
Hi

I apologize for the confusion. My github pages is activated. My first assignment was checked on the same basis.

Right now,  I have again checked it again on my end. Can you please verify? Here's the link.

https://rishankumb.github.io/cs460student/02/


Best regards,
Rishank Singh
________________________________

**Comment by gaiborjosue** [comment]
Hello,

Thanks for activating your GitHub pages. I will check the rest of your code with that. However, I will still have to deduct some points due to the deadline for the submission. Thanks!

**Comment by rishankumb** [comment]
I am sorry but I haven't activated it right now. I activated my github pages before my first assignment. Please consider and please do not deduct my points. I worked very hard on this assignment.
________________________________

**Pull request closed without merging**
